name: 'gp24'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pandas=2.2
    - ipykernel=6.29
    - altair-all=5.3
    - dash=2.18
    - dash-bootstrap-components=1.7
    - plotly=6.0
    - tabulate=0.9  # df.to_markdown()
    - lxml=5.3  # pd.read_html()
    - pip=24.0
    - pip:
        - dash-vega-components==0.0.1
        - geopy==2.4.1